#-------------------------------
# General Site Settings

title: Avi Michael </br> Digital Producer
description: Video and Digital Producer 
email: playrightproductions@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: Clients, url: '#clients'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Avi Michael is a digital producer and is the proprietor of Play Right Productions'
  rel-author: ''
  rel-publisher: ''

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  **Avi specialises in producing digital content** that is informative, accessible and entertaining.
  He has worked as a [video and film producer](http://www.playrightproductions.com.au){:target="_blank"},
  and a [photographer](http://www.avimichaeldp.com){:target="_blank"} and so he has a truely end-to-end understanding of the digital content production workflow.


skills:
- {name: Communication, value: '8'}
- {name: Organization, value: '7'}
- {name: Learning, value: '8'}
- {name: Teaching, value: '10'}
- {name: Planning, value: '7'}
- {name: Visual Design, value: '5'}
- {name: UX Design, value: '6'}
- {name: Programming, value: '5'}

#-------------------------------
# Work Section

projects:
- {name: TYPO International Design Talks, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: City-IN website concept, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Crispy Icons, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Flat Mobile UI/UX Concept, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Fresh It Up, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: Timeline Page, folder: 'proj-6', file: 'work/proj-6.html'}
- {name: Weather Dashboard, folder: 'proj-7', file: 'work/proj-7.html'}
- {name: Stripes & Co, folder: 'proj-8', file: 'work/proj-8.html'}




#-------------------------------
# Clients Section

clients:
- {avatar: 'face-aaroni.jpg',
  name: 'Dani Kopoulos',
  title: 'Program Director, The Educational Arts Team',
  quote: '<p><strong>Avi had a strong attention to detail</strong> and a --- ---.</p>',
  logo: 'logo1.png'}
- {avatar: 'face-atariboy.jpg',
  name: 'Sabrina Dridje',
  title: 'Director, The Made in NY Media Center',
  quote: '<p><strong>Working with Avi was awesome.</strong> He often gets things.</p>',
  logo: 'logo2.png'}
- {avatar: 'face-jackiesaik.jpg',
  name: 'Stacy Lang',
  title: ', Quebec Int.',
  quote: '<p><strong>Yea, I guess hes good at computers or something,</strong> but let me ask you this: If a cat always lands on its feet, and buttered bread always lands butter side down, what would happen if you tied buttered bread on top of a cat?</p>',
  logo: 'logo3.png'}



#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'http://twitter.com/playrightp'}
- {icon: 'youtube', link: 'https://www.youtube.com/channel/UCiO7juku206oPrHyarxr6bA'}
- {icon: 'linkedin', link: 'https://au.linkedin.com/in/avi-michael-27a0a8103'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
